name: ShvanHazizCONV

options:
  bundleIdPrefix: com.neeko
  deploymentTarget:
    iOS: "17.0"

targets:
  ShvanHazizCONV:
    type: application
    platform: iOS
    sources:
      - path: ShvanHazizCONV
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neeko.shvanhazizconv
        SWIFT_VERSION: 5.9
        CODE_SIGNING_ALLOWED: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: ShvanHazizCONV/Info.plist

schemes:
  ShvanHazizCONV:
    build:
      targets:
        ShvanHazizCONV: all
