name: ShvanHazizCONV

options:
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.shvanhazizconv
    INFOPLIST_FILE: ShvanHazizCONV/Info.plist
    IPHONEOS_DEPLOYMENT_TARGET: "17.0"
    SWIFT_VERSION: "5.9"

targets:
  ShvanHazizCONV:
    type: application
    platform: iOS
    sources:
      - path: ShvanHazizCONV
