name: ShvanHazizCONV
options:
  deploymentTarget:
    iOS: "17.0"
settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.nehadkurd.shvanhazizconv
    INFOPLIST_FILE: ShvanHazizCONV/Info.plist
    SWIFT_VERSION: "5.9"

targets:
  ShvanHazizCONV:
    type: application
    platform: iOS
    sources:
      - path: ShvanHazizCONV
    settings:
      base:
        DEVELOPMENT_TEAM: ""
        CODE_SIGN_STYLE: Manual
        CODE_SIGNING_ALLOWED: "NO"
        CODE_SIGNING_REQUIRED: "NO"
        CODE_SIGN_IDENTITY: ""
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        CURRENT_PROJECT_VERSION: "1"
        MARKETING_VERSION: "1.0"
