name: ShvanHazizCONV

options:
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    PRODUCT_BUNDLE_IDENTIFIER: com.example.shvanhazizconv
    INFOPLIST_FILE: ShvanHazizCONV/Info.plist
    SWIFT_VERSION: "5.8"
    SWIFT_OPTIMIZATION_LEVEL: "-Onone"

targets:
  ShvanHazizCONV:
    type: application
    platform: iOS
    sources:
      - path: ShvanHazizCONV
