name: ShvanHazizCONV
options:
  bundleIdPrefix: com.neeko
targets:
  ShvanHazizCONV:
    type: application
    platform: iOS
    deploymentTarget: "17.0"
    sources:
      - path: ShvanHazizCONV
    settings:
      base:
        SWIFT_VERSION: 5.9
        CODE_SIGNING_ALLOWED: NO
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
    info:
      path: ShvanHazizCONV/Info.plist
