name: ShvanHazizCONV

options:
  bundleIdPrefix: com.neeko
  deploymentTarget:
    iOS: 17.0

targets:
  ShvanHazizCONV:
    type: application
    platform: iOS
    sources:
      - path: ShvanHazizCONV
    info:
      path: ShvanHazizCONV/Info.plist
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.neeko.shvanhazizconv
        MARKETING_VERSION: 1.0
        CURRENT_PROJECT_VERSION: 1
        CODE_SIGNING_ALLOWED: NO
